version: '2'
services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./docker_volumes/mongo:/data/db
    logging:
      driver: none
  dev:
    image: node:6-alpine
    ports:
      - "4040:4040"
    environment:
      - NODE_ENV=development
      - PARSE_HOST=vm1.dev
      - MONGODB_URI=mongodb://mongo
    working_dir: /app_root
    # command: npm run dev-prod
    command: npm run dev
    volumes:
      - .:/app_root
    depends_on:
      - mongo
